# Generated by Django 4.1.1 on 2022-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('slno', models.IntegerField()),
                ('product', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.IntegerField()),
                ('bname', models.CharField(max_length=20)),
                ('baddress', models.CharField(max_length=200)),
                ('bphonenumber', models.IntegerField(max_length=12)),
                ('sname', models.CharField(max_length=30)),
                ('saddress', models.TextField()),
                ('sphonenumber', models.IntegerField(max_length=12)),
            ],
        ),
    ]
